sudo: false
language: node_js
node_js:
    - stable
    - '0.12'
env:
    - NODE_ENV=development
script:
   - npm run lint
install:
    - npm install
    # - cp _config/task.task-name.js test/mock-project/_config/task.task-name.js
    # - cp package.json test/mock-project/package.json
    # - cd test/mock-project
    # - npm install
    # - npm install gulp
    # - cd ../..
    # - npm install mocha -g
    # - npm install gulp-cli -g
# script:
#     - mocha
cache:
  directories:
    - node_modules
    # - test/mock-project/node_modules
git:
  depth: 1
