language: node_js
cache:
  directories:
    - ~/.npm
    - node_modules
notifications:
  email: false
node_js:
	- stable
  - '9'
  - '8'
  - '6'
  - '4'
env:
	- NODE_ENV=development
script:
	- npm run lint
after_success:
  - npm run travis-deploy-once "npm run semantic-release"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
